[Distribution]
Distribution=opensuse
Release=15.6

[Output]
Format=directory
Bootable=no

[Package]
Packages=systemd
        systemd-sysvinit
        util-linux
        bash
        coreutils
        glibc-locale
        openSUSE-release
        zypper
        rpm
        kernel-default
        bootloader
        grub2
        grub2-x86_64-efi
        syslinux

[Content]
RemovePackages=vim
